### ISSUE TITLE
vaadin sass compiler is not told file name when compiling

### ISSUE THREAD

**Issue by tveimo** [j-a-w-r/jawr-main-repo#18]
Am trying to fix issues with some scss files, but am getting error messages like 

23:08:18.611 ERROR c.v.s.i.h.SCSSDocumentHandlerImpl.log(70)                    Error when parsing file 
null on line 2, column 12
23:08:18.613 ERROR c.v.s.i.h.SCSSDocumentHandlerImpl.log(75)                    encountered ":". Was expecting one of: "," ")" 
org.w3c.css.sac.CSSParseException: encountered ":". Was expecting one of: "," ")" 

Is it possible to tell the sass compiler the name of the file that is being compiled?

**Comment by ic3fox** [comment]
Hi

I've made a test with a wrong scss file and I'm getting the proper reference of the file in the log.

{code}
SEVERE: Error when parsing file 
/css/generator/sass/_partial-for-import.scss on line 6, column 24
{code}

Can you please give me the files which are causing this issue so I could test?
If these files are sensitive, you can send them to me privately.

Cheers,

**Comment by ic3fox** [comment]
Hi

Do you have any news about this issue?

**Comment by ic3fox** [comment]
This issue is closed.
You can reopen it, if you still encounter this issue.

Cheers,
