### ISSUE TITLE
jawr:script tag doesn't include "gzip_" prefix in url when CDN proxy doesn't advertise "accept-encoding: gzip" request header

### ISSUE THREAD

**Issue by tveimo** [j-a-w-r/jawr-main-repo#24]
I've got content that is served through a CDN. The CDN fetches content on-demand from my server. For some reason the URL that is generated from a jawr:script/style tag doesn't contain the gzip_ prefix in those cases. 

<script type="text/javascript" src="//cdn.com/resources/N814034619/bundles/core.js" ></script>

instead of 

<script type="text/javascript" src="//cdn.com/resources/gzip_N814034619/bundles/core.js" ></script>

I've been unable to determine why, but am thinking it might be due to the CDN server not including a  "accept-encoding: gzip" header? If I fetch the content with a web browser, the url generated for these resources contains the gzip_ prefix.

**Comment by tveimo** [comment]
I don't mind if the content is not served with gzip compression in this case, but the jawr css / js resources servlet returns a 404 when the browser (which does advertise "accept-encoding: gzip") fetched the resource without the gzip_ prefix. I guess it could return content on the url with and without the gzip_ prefix irregardless of the client advertising gzip support.

**Comment by ic3fox** [comment]
Hi,

I've not been able to reproduce your issue.
Perhaps I did not properly understand the case.

The jawr:script/style tag renders "gzip" prefixed path if the request header contains "accept-encoding: gzip".
If it's not the case, it will not been prefixed by "gzip_".
But in any case, when requesting "gzip" or "non gzip" bundle, Jawr will returns the requested bundles.
Jawr creates this 2 types of bundles (gzip and non gzip) when processing the bundles.

 The "accept-encoding: gzip" header is only taking in account when generating the URL in the tag. 

You can make a test to check if your bundle exists using your browser.
You take the "gzip" URL, then you remove the prefix "gzip_" in the bundle, and Jawr will serve you the non gzipped bundle.

So if your URL is like http://mydomain.org/gzip_987978/js/myBundle.js, you can get the non gzipped version using the URL   http://mydomain.org/987978/js/myBundle.js

Let me know if the bundle is correctly rendered.

Cheers,

**Comment by ic3fox** [comment]
Hi

Do you have any news about this issue?

**Comment by tveimo** [comment]
Sorry, been very busy elsewhere. I'll try to put together a test case, but here's what I think is happening;

Our CDN server (keycdn.com), doesn't advertise accept-encoding: gzip when fetching anything that's not images or css files. Thus the JAWR script/style taglib doesn't include the gzip_ prefix in the resource urls.

It does however advertise accept-encoding: gzip when fetching the images / css files, but the JAWR servlet doesn't accept fetching a resource with gzip encoding, unless the gzip_ prefix is included in the resource path.

**Comment by ic3fox** [comment]
Hi,

So your resource are served by your web application through the CDN.

Can you confirm me that your are not using the preprocessing feature?

`jawr.use.bundle.mapping=true`

Cheers,

**Comment by tveimo** [comment]
I do have this line in jawr.properties yes

jawr.use.bundle.mapping=true

**Comment by ic3fox** [comment]
Do you have the following property in your config?

`jawr.strict.mode=true`

If so, can you update your config and use : 

`jawr.strict.mode=false`

**Comment by tveimo** [comment]
Hi, just bumped into this problem again. We have strict mode set to false. I can send you a test url by private message to show the problem, if you like?

**Comment by tveimo** [comment]
Unsure if related, but the JawrRequestHandler seems to only serve resources with the gzip_ prefix even when jawr.gzip.on=false.

**Comment by ic3fox** [comment]
Hi,

You can send me the test url in private message.
Is this behaviour constant or it appears then disappears?

Cheers,

**Comment by tveimo** [comment]
I found that this issue seems to be resolved on 3.9, it serves resources both with and without gzip_ prefix. I was using 3.8 until recently.
