### ISSUE TITLE
Incomplete artifacts in maven centra repo

### ISSUE THREAD

**Issue by pakmans** [j-a-w-r/jawr-main-repo#41]
I was trying to update a project from 3.3.3 to 3.9, but neither 3.8 nor 3.9 are in maven central repo.
Well, they are, but incomplete.  The jar is missing.

**Comment by ic3fox** [comment]
Hi,

The structure of Jawr has change since the version 3.3.3

Now Jawr is separated in multiple modules.
You have to change your dependency to use : 

```xml
<dependency>
    <groupId>net.jawr</groupId>
    <artifactId>jawr-core</artifactId>
    <version>3.9</version>
</dependency>
```

Please check the migration guide to see the different actions to do for your migration : https://jawr.java.net/migrationGuide.html

Cheers,
