### ISSUE TITLE
Jawr yaml properties seem to not picked up properly

### ISSUE THREAD

**Issue by arapost-bmj** [j-a-w-r/jawr-main-repo#46]
Hi,

I faced the following issue: I setup a spring boot application with jawr and thymeleaf and I added all the jawr properties in the common yaml format. I noticed that specific properties were not picked up at all, and specifically the following: 

`
jawr:
    debug: 
        on: true
    gzip: 
        on: false
`
I doubled check if there was any indent issue in my yaml file and it seemed fine. When I changed the format specifically for the jawr properties, all properties were picked up correctly. The format now looks like this: 
jawr.debug.on: true
jawr.gzip.on: false
...
After having a chat with @dtrunk90 , it could be a side effect of using a single map for all jawr properties, implementation is here: https://github.com/j-a-w-r/jawr-main-repo/blob/master/jawr-spring/jawr-spring-extension/src/main/java/net/jawr/web/autoconfigure/JawrProperties.java

Thanks

**Comment by ic3fox** [comment]
Hi,

Can you tell me if only the properties **jawr.debug.on** and **jawr.gzip.on** are not taking in account?

Cheers,

**Comment by ic3fox** [comment]
Hi,

I've been able to reproduce your issue.
In fact it was due to an error in your yaml configuration file.
The spring YAML parser consider the **on** attribute name as a value for **true**

You have to declare your yaml configuration file like below 
Please note the single quote before and after the **on** attribute name. 

```yaml
 jawr:
   debug:
        'on' : false
    gzip:
        'on' : true
```

Cheers,

**Comment by arapost-bmj** [comment]
Thank you very much for the response!
