### ISSUE TITLE
JAWR 3.3 + UglifyJS - application startup time has increased to 24 minutes

### ISSUE THREAD

**Issue by kalindir** [j-a-w-r/jawr-main-repo#47]
I had a question that I also posted on https://java.net/jira/browse/JAWR-313

I am using JAWR 3.3.3 for bundling my JS and CSS files in my application. I am currently using YUICompressor for compressing the files, however, because YUICompressor is not compatible with ES6's Promises' catch, I was exploring using UglifyJS instead with my current JAWR version. I dropped in the appropriate UglifyJS files from the latest JAWR version and got it to work, however, my server startup is now taking 24 minutes! When I used uglify-js via command line, however, I did not see it taking a long time. Can you shed light on any ideas for troubleshooting this? Any help is highly appreciated. Thanks!

**Comment by ic3fox** [comment]
Hi,

Jawr 3.3.3 use rhino as Javascript engine.
The compression speed is not really dependent of Jawr.
This could be an issue in the way rhino handle your version of UglifyJS

I'm seeing 2 solutions : 
- Use the built in JSMin minificator.
- You can try to upgrade to Jawr 3.9 and use nashorn, the built in Java JS  engine and see if the processing speed is better.

You can send me an sample of JS file to minify so I'll take a look but I'm not optimistic about being able to speed up the minification process as it is not an intrinsic Jawr issue but the use of other components.

Cheers,

**Comment by kalindir** [comment]
I am using nashorn JS engine and the application server start up time is still very slow - 15 minutes in total. Our team was tending towards using UglifyJS instead of JSMin because of the number of NPM downloads and active community. If you have any other troubleshooting tips, that would really help. (Not sure I can share any JS files - these are confidential )

**Comment by ic3fox** [comment]
Hi,

Have you make a test directly with nodejs?
I would be interested to know how much is the gain.

If the gain is substantial, we should probably consider using nodejs as the execution engine for this kind of process.

Cheers,

**Comment by ic3fox** [comment]
Hi,

As said the issue is not related to Jawr itself.
If you would like to have the possibility to use nodeJS as JS engine, please open a new issue.

Cheers,
