### ISSUE TITLE
Child bundles are loaded instead of parent because the bundle ids are the same

### ISSUE THREAD

**Issue by maximmold** [j-a-w-r/jawr-main-repo#52]
I'm seeing an issue where the child content is being loaded instead of the parent because the child is assigned the same bundle name as the parent.

**Comment by maximmold** [comment]
I've added a fix in the following pull request: https://github.com/j-a-w-r/jawr-main-repo/pull/50/commits

**Comment by ic3fox** [comment]
Hi,

Good catch and thanks for the fix.

Cheers,

**Comment by ic3fox** [comment]
Hi,

Can you make a pull request only with the fix of this issue?
It's easier to manage and merge them, when they're related to a specific issue.

Cheers,

**Comment by maximmold** [comment]
Yeah, I'll try to branch my fork and figure out how to do that on Monday.
Still getting familiar with git.

**Comment by maximmold** [comment]
I've figured it out. Here it is. https://github.com/j-a-w-r/jawr-main-repo/pull/55

**Comment by ic3fox** [comment]
This issue has been fixed in the master branch.
Thanks for your pull request
