### ISSUE TITLE
When bundles are rebuilt old cache entries are not removed

### ISSUE THREAD

**Issue by maximmold** [j-a-w-r/jawr-main-repo#54]
When bundles are rebuilt old cache entries are not removed resulting in leaked memory for the old version of the bundle.

**Comment by maximmold** [comment]
2nd commit in https://github.com/j-a-w-r/jawr-main-repo/pull/53 should fix it, but not sure how it would work for the variant bundles.

**Comment by ic3fox** [comment]
Hi,

What do you mean by leaked memory?
The intent of the original code was that the rebuilt of the bundles will update the cache entries, so the old version is updated after the rebuilt.

What is exactly the issue which you're facing?

Cheers

**Comment by maximmold** [comment]
I was seeing that there is a cache entry for the old bundle ID after
reloading, as well as one for the new bundle ID. I would expect that bundle
ID to never be accessed again due to the nature of cache busting. I did not
verify whether the value was actually updated, but even if it was updated,
it seems like it would never be utilized.
Thanks!
Max

**Comment by ic3fox** [comment]
Ok. I've got it.
So you've deleted a bundle and create a new one.
I'll check this case.

Cheers,

**Comment by maximmold** [comment]
Created a new pull request with just this change here: https://github.com/j-a-w-r/jawr-main-repo/pull/56

**Comment by ic3fox** [comment]
The issue has been fixed in the master branch
Thanks for reporting the issue and providing the PR
