### ISSUE TITLE
Update "Spring integration" documentation page with jawrBinaryController

### ISSUE THREAD

**Issue by mpscheidt** [j-a-w-r/jawr-main-repo#72]
[Spring MVC integration](https://j-a-w-r.github.io/integration/spring.html) documentation talks about mapping both css and image files to `jawrCSSController`. That doesn't seem to work. Rather, a separate binary controller should be declared and mapped for images (and fonts). Just like the sample app does:

	<bean id="jawrJsController" parent="jawrBase" />

	<bean id="jawrBinaryController" parent="jawrBase">
		<property name="type" value="binary" />
	</bean>
      
	<bean id="jawrCSSController" parent="jawrBase">
		<property name="type" value="css" />
	</bean>

	<bean id="urlMapping" class="org.springframework.web.servlet.handler.SimpleUrlHandlerMapping">
		<property name="mappings">
			<props>
				<prop key="/jawr/**/*.js">jawrJsController</prop>
				<prop key="/jawr/**/*.css">jawrCSSController</prop>
				<prop key="/jawr/**/*">jawrBinaryController</prop>
			</props>
		</property>
	</bean>

Please update the Spring MVC integration page accordingly.

**Comment by ic3fox** [comment]
The documentation has been updated.

Thanks for the report
