### ISSUE TITLE
Versioning of jawr bundles to fix cache issue.

### ISSUE THREAD

**Issue by munawwerali** [j-a-w-r/jawr-main-repo#78]
When we are modifying any individual file we need to forcefully clear the cache to get the latest changes so instead of clearing the cache manually It would be good if we add versioning to generated bundles so it will always fetch the latest generated bundle.

**Comment by ic3fox** [comment]
Hi

This is the current behaviour of Jawr.
Whenever a bundle change a hashcode is calculated, which is used in the bundle path to force the retrieve of the latest bundle.

Can you tell me in which case it doesn't work for you?

Cheers,

**Comment by munawwerali** [comment]
Hi,

Thanks for your comments, yes it's working fine, it was coming in an
environment where jawr was disabled, and I thought it is not there in jawr.

Thanks

**Comment by ic3fox** [comment]
Great.

I'm closing this issue.

Cheers,
