### ISSUE TITLE
Binary resource path wrong in debug mode

### ISSUE THREAD

**Issue by darkof78** [j-a-w-r/jawr-main-repo#79]
When jawr is started in debug mode image path is set to css servlet path instead of image (binary) servlet path.
In production mode everything is OK.

JawrServlet - type css - /jawrcss/
JawrServlet type binary - /jawrsprite/

debug mode:

https://localhost:8443/jawrcss/images/image.png NOT OK
instead of
https://localhost:8443/jawrsprite/images/image.png

production mode:

https://localhost:8443/jawrsprite/cb1004436932/images/image.png  OK

**Comment by ic3fox** [comment]
Hi,

It is normal thatthe resource in debug mode goes to the CSS servlet. In fact, the CSS servlet forward the don't handle the request and forward it.

The reason for that is to be able to handle images from Css resources where the images path are relative to the CSS file.

If you encounter a particular use case, where this doesn't work, please give me more detail about it.
A sample project where I can reproduce the issue would be helpful.

Cheers,

**Comment by darkof78** [comment]
Hi,

thanks for the explanation.

Best Regards,
Darko
