### ISSUE TITLE
Update Spring and Thymeleaf version

### ISSUE THREAD

**Issue by arulthangaraj** [j-a-w-r/jawr-main-repo#80]
Library not working with spring boot 2.0 which uses spring framework version 5.0.4.RELEASE. 
WebMvcAutoConfiguration package is moved to org.springframework.boot.autoconfigure.web.servlet

**Comment by arulthangaraj** [comment]
Please let me know if there are any plans to update the library to use the latest version on spring libraries

**Comment by ic3fox** [comment]
The fix for this issue will be integrated in the next release.

Cheers
